### ISSUE TITLE
World Ferns 2146 of 2020-06-14, of 1140 of 2020-06-26: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#146]
**2020-06-22:**   @gdower 
Frontend version: c99dba2 June 17, 2020 9:47 AMBackend version: 507800e June 17, 2020 8:53 AM

- [x] Missing subfamilies in the classification (SF):
There are 32 subfamilies in the source file: 
Lycopodioideae W. H. Wagner   &amp; Beitel ex B. &Oslash;llg.
Huperzioideae W. H.   Wagner &amp; Beitel ex B. &Oslash;llg.
Lycopodielloideae W. H. Wagner &amp; Beitel ex   B. &Oslash;llg.
Mankyuoideae J. R.   Grant &amp; B. Dauphin
...  and also:
45.9 | uncertain
48.1 | Pteridryoideae ined.
48.2 | Arthropteridoideae   ined.
48.3 | Tectarioideae ined.

- [x] There is also rank T for tribe in the source file. However, there are only two records, and they refer to clades: 
    Amauropeltoid clade
    Cyclosoroid clade
Should be excluded from CoL. Both are not present in the classification, but names appear in the workbench.

- [x] Suborder _Saccolomatineae_ is incorrectly placed as a genus (bug in the source file? there is no such status as SO):
![image](https://user-images.githubusercontent.com/28574252/85308594-fe12b180-b476-11ea-8419-27cf4036f272.png)
(I failed to find name _Saccolomatineae_ in the source file).
I can block the name in the Clearinghouse.

**Comment by yroskov** [comment]
- [ ] Missing infraspecific marker in synonyms:
![image](https://user-images.githubusercontent.com/28574252/85311722-77ac9e80-b47b-11ea-8e6f-f287d072b60d.png)

In the source file: 
= Saccoloma brasiliense var. nigrescens (Kunze) Hieron. [Hedwigia 47: 207 (1908)] 
= Saccoloma inaequale var. brasiliense (C. Presl) Luetzelb. [Estud. Bot. Nord&eacute;ste 3: 250 (1923)]

**Comment by yroskov** [comment]
2020-06-22, new import
- [ ] Is it our top up in the field AccordingTo?
![image](https://user-images.githubusercontent.com/28574252/85321229-f7da0080-b489-11ea-9a5d-8e68bd01f769.png)
Shall we keep LTS field empty in the case of WFerns/Plants - as we agreed with Markus?

**Comment by yroskov** [comment]
- [ ] There are no classes in a new version of WFerns. YR should assemble orders in two classes (Lycopodiopsida & Polypodiopsida) during production assembly.

**Comment by yroskov** [comment]
- [ ] YR should fill metadata before production assembly. Check details with Michael.

**Comment by yroskov** [comment]
**Issues**
- [ ] Name Match None. https://data.catalogue.life/catalogue/2145/dataset/2146/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=name%20match%20none&limit=100&offset=0 
Looks like incorrect parsing.

- [ ] Indetermined. https://data.catalogue.life/catalogue/2145/dataset/2146/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=indetermined&limit=100&offset=0
As appears in the clearinghouse:
![image](https://user-images.githubusercontent.com/28574252/85322823-8780ae80-b48c-11ea-9dc2-aa06446f6596.png)
 In the source file: Goniopteris venusta (Heward) comb. ined. var. usitata (Jenman) comb. ined.

**Comment by yroskov** [comment]
- [ ] Subspecies Assigned. https://data.catalogue.life/catalogue/2145/dataset/2146/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=subspecies%20assigned&limit=100&offset=0

Looks like incorrect parsing of the authorstring. As appears in the clearinghouse:
![image](https://user-images.githubusercontent.com/28574252/85327627-ed713400-b494-11ea-8ce3-53fd78c36517.png)
Should be: Asplenium octoploideum Viane & van den Heede

**Comment by gdower** [comment]
I fixed the subfamily, tribe, suborder, and LTS issues.

**Comment by yroskov** [comment]
Well, we'll have such case (no idea, how to deal with it in our environment):
![image](https://user-images.githubusercontent.com/28574252/85330761-9bcba800-b49a-11ea-93e9-883225014e7a.png)

**Comment by yroskov** [comment]
- [ ] Name Match Ambiguous https://data.catalogue.life/catalogue/2145/dataset/2146/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=name%20match%20ambiguous&limit=100&offset=0
![image](https://user-images.githubusercontent.com/28574252/85331107-214f5800-b49b-11ea-8b71-61633956318a.png)
Portion **comb. ined.** removed by Clearinghouse

**Comment by yroskov** [comment]
- [ ] Id Not Unique https://data.catalogue.life/catalogue/2145/dataset/2146/verbatim?issue=id%20not%20unique
Geoff, should we (can we) do anything with these names?

**Comment by mdoering** [comment]
@gdower do you know how to configure the name parser for `Asplenium octoploideum Viane & Van den heede`?

**Comment by mdoering** [comment]
> Id Not Unique https://data.catalogue.life/catalogue/2145/dataset/2146/verbatim?issue=id%20not%20unique

Looks like the UUID is linked to the name, probably from GNParser?
@gdower in which case you can simply drop the duplicate names

**Comment by gdower** [comment]
@mdoering, to configure the name parser would I POST something like below to /parser/name/config ?

```JSON
[
  {
    "scientificName": "Asplenium octoploideum Viane & Van den heede",
    "authorship": "Viane & Van den heede",
    "rank": "species",
    "genus": "Asplenium",
    "specificEpithet": "octoploideum",
    "code": "BOTANICAL",
    "type": "SCIENTIFIC",
    "remarks": "Fixing parsing of author Van den heede",
  }
]
```

**Comment by yroskov** [comment]
- [ ] Inconsistent Authorship. Seems, incorrectly parsed autjorstrings with subgenera in synonyms
![image](https://user-images.githubusercontent.com/28574252/85438723-e52afe80-b551-11ea-9689-f552b7e7b3f6.png)
  
https://data.catalogue.life/catalogue/2145/dataset/2146/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=inconsistent%20authorship&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS**
![image](https://user-images.githubusercontent.com/28574252/85439486-a8133c00-b552-11ea-96ab-12645d0a2a33.png)

**Comment by yroskov** [comment]
Identical genus
![image](https://user-images.githubusercontent.com/28574252/85443062-73a17f00-b556-11ea-931b-6c3a1fa4f200.png)

**Comment by yroskov** [comment]
**RESOLVED TASKS** (2020-06-23):

![image](https://user-images.githubusercontent.com/28574252/85444861-5ff71800-b558-11ea-9522-19a7e3b4043e.png)

**Comment by mdoering** [comment]
@gdower for existing parser configs please see https://api.catalogue.life/parser/name/config

You need to have an ID property that is made up from the name and authorship separated by a pipe. These are the raw strings that if the parser encounters them uses the preconfigured parsed name. The scientificName should be without authors and the authorship parsed:

```
[
  {
    "id": "Asplenium octoploideum|Viane & Van den heede",
    "scientificName": "Asplenium octoploideum",
    "authorship": "Viane & Van den heede",
    "rank": "species",
    "genus": "Asplenium",
    "specificEpithet": "octoploideum",
    "combinationAuthorship": {
        "authors": [
          "Viane",
          "Van den heede"
        ]
    },
    "code": "BOTANICAL",
    "type": "SCIENTIFIC",
    "remarks": "Fixing parsing of author Van den heede"
  }
]
```

**Comment by gdower** [comment]
I think the reason Vittaria is not in the duplicates genus report is because `auct.` is parsed incorrectly as a species epithet:

![image](https://user-images.githubusercontent.com/8573609/85631105-87beac80-b63a-11ea-9025-a698f7211454.png)

I'm supplying that record as:

ID | scientificName | authorship | rank | uninomial | genus | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
64f5bbfb-5d43-54f7-b4e3-2dc7924a2aa3 | Vittaria auct. | auct. | genus | Vittaria |   |   |   |   |   | botanical |   |   |  

I tried to correct it with the following name parser config, which [didn't work](http://api.catalogue.life/parser/name?name=Vittaria%20auct.):

```JSON
[
  {
    "id": "Vittaria|",
    "scientificName": "Vittaria auct.",
    "authorship": "",
    "appendedPhrase": "sensu auct.",
    "rank": "genus",
    "genus": "Vittaria",
    "code": "BOTANICAL",
    "type": "SCIENTIFIC",
    "remarks": "Fixing parsing of the genus Vittaria which was getting interpreted as the non-existent species, 'Vittaria auct'"
  }
]
```

**Comment by mdoering** [comment]
@gdower the id bit is wrong and the most important part!
It defines when the config kicks in and it has to match the incoming raw string. The parser checks for both a pure name match without authorship and both together.
The id is made up from 2 parts, scientificName and authorship. In your config the name=Vittaria and authorship is none.

But the raw string has `Vittaria auct.` and `auct.` so it probably needs to be:

```
[
  {
    "id": "Vittaria auct.|auct.",
    "scientificName": "Vittaria",
    "authorship": "",
    "appendedPhrase": "sensu auct.",
    "rank": "genus",
    "genus": "Vittaria",
    "code": "BOTANICAL",
    "type": "SCIENTIFIC"
  }
]
```

I will check this in test code first.
Please delete the wrong config, otherwise we might get unexpected results.
You can do so by issuing `DELETE /parser/name/config/Vittaria|`

`Name.appendedPhrase` does not exist in the new data model anymore. I might have to also adapt the ParserConfig class in my current refactoring, will report. Please keep this config open for now

**Comment by mdoering** [comment]
I think this one is better properly fixed in the name parser

**Comment by gdower** [comment]
@mdoering, I deleted the previous parser config and posted yours. It still [doesn't work](http://api.catalogue.life/parser/name?name=Vittaria%20auct.) although maybe it depends on CatalogueOfLife/data#146.

**Comment by mdoering** [comment]
No. Its on dev now but will let you know when we get it to prod, hopefully by monday

**Comment by yroskov** [comment]
**Order Marattiales is missed** in crawled dataset due to a bug in source file:
G | 7 | Marattiales Link                   (should be O)

**Comment by yroskov** [comment]
**2020-06-25:**

All Editorial Decisions have been successfully moved from Hassler Plants project (gsd 2146) to production project col-draft 3.

**Comment by yroskov** [comment]
**Assembly of WFerns 1140 in project 3, 2020-06-26:**

@mdoering @gdower 
I was not able to complete unification of split genus _Cheilanthes_ in project 3. Reason: before (2020-06-24) I was able to complete **sync for entire species cluster** in nested sector using sync option in the GSD tree (right); sync option was available in GSD window. Now sync option in GSD window is absent:
![image](https://user-images.githubusercontent.com/28574252/85868219-99fe2f00-b78f-11ea-8c1c-6fe0ce9d7887.png)

The only available option now is to do sync species by species in assembly tree on the left. It's impossible manual work. 
@gdower we probably should go back to our idea of resolving issue of split genera in your conversion code. The Clearinghouse is not suitable for such operation.

**Comment by mdoering** [comment]
@yroskov please dont modify data in the source conversion. It would be much better to show the data as it is in the Clearinghouse. 

The sync button only shows when a sector exists. That does not seem to be the case in the draft as you can see by the missing icon. Maybe the sectors were not copied properly? What does the sector interface say?

**Comment by mdoering** [comment]
Is it correct you still use the old ACEF version of ferns (1140) for your work? I thought this is about getting the latest ColDP version in.

**Comment by mdoering** [comment]
there is one broken sector apparently: https://data.catalogue.life/catalogue/3/sector?broken=true&limit=100&offset=0&subjectDatasetKey=1140

And 3 Cheilanthes sectors: https://data.catalogue.life/catalogue/3/sector?limit=100&name=Cheilanthes&offset=0
Are the species split across 4 different places?

**Comment by mdoering** [comment]
The Hassler project uses the ColDP dataset as I expected. The sectors (and probably also decisions) have been copied wrongly to the draft and got applied to the ACEF dataset which does not have any split genera!

https://data.catalogue.life/catalogue/2145/sector?limit=100&offset=0&subjectDatasetKey=2146

We should be careful in hosting the same dataset in different versions/formats at the same time in the Clearinghouse. Like I mentioned before this is asking for troubles as the datasetKey changes. It would be better to do tests and even temporary assemblies on dev. Or we might even need another more stable environment. 1040 should be and remain the datasetKey for ferns, not the new 2146. We will lose all import history and metrics.

**Comment by mdoering** [comment]
well, now that the new sectors use 1040 it might be a good oppertunity to just import the ColDP dataset into 1040 so we can keep the key stable and have the latest data

**Comment by yroskov** [comment]
2020-06-29
Tests of GSD **1140 in CoL 2020-06-26** at http://dev4.species.id:2204/col_plus via AC interface

- [ ] Unexpected credits to CoL Management Classification:
![image](https://user-images.githubusercontent.com/28574252/86010052-8564a580-b9e0-11ea-9bcb-4bf3501c0288.png)
What does it mean?

**Comment by yroskov** [comment]
- [ ] Fixes in **Identical genus** (four split genera), detailed analyses:
                    csv source vs CoL-draft
Cheilanthes 5+1+24+50=80 vs 68    **LOST**
Doryopteris 7+9+30=46  vs   46
Grammitis 35+6+4+1=46   vs   46
Vittaria 7+15=22   vs  22

**Comment by yroskov** [comment]
Mess in automatically generated Taxonomic Coverage after sector fixes in Clearinghouse:
![image](https://user-images.githubusercontent.com/28574252/86020958-2d34a000-b9ee-11ea-8e5a-ba22db76bef3.png)

**Comment by mdoering** [comment]
what would you expect?

**Comment by yroskov** [comment]
- [ ] **Critical problems with Complex Decisions**: names, corrected via Complex Decisions did not pass in final product, or passed in incorrect form.
3 cases of misparced authorstrings (Van den heede) have been corrected in the Clearinghouse via Complex Decisions, but these names, seems, did not appear in final product:
Asplenium octoploideum Viane & Van den heede
Asplenium x chasmophilum Van den heede & Viane
Asplenium x ligusticum R. Bernardello, Marchetti, Van den heede & Viane

Another case: mistake in the source file "Lellingeria barbensis (Lellinger) A. R. Sm. er R. C. Moran" was corrected as "Lellingeria barbensis **(Lellinger) A. R. Sm. et R. C. Moran**" (complex decision). The name appears in final product as "Lellingeria barbensis **R. C. Moran**" (i.e. with incorrect authorstring) 

Name was corrected as "Sceptridium rugulosum **(W.H.Wagner) Škoda & Holub**", but it appears in final product as "Sceptridium rugulosum **(W. H. Wagner) Å**"

**Comment by mdoering** [comment]
@yroskov can you please leave links to where the problems are? is final product the legacy portal? 
What exactly are the decisions?

Remember we decided not to use the parsed authorships but instead use the verbatim form in the ac-exports.
This has actually been removed today with the new scrutiny branch being deployed to prod, as we keep the verbatim authorship now. But this needs a reimport and resync to get applied everywhere

**Comment by mdoering** [comment]
The draft contains [Lellingeria barbensis (Lellinger) A.R.Sm. & R.C.Moran](https://data.catalogue.life/catalogue/3/taxon/2355fd5a-11fb-469c-a114-850c0e6e8ce2)

But the verbatim data is:
```
col:scientificName = Lellingeria barbensis (Lellinger) A. R. Sm. er R. C. Moran
col:authorship = R. C. Moran
```

So the wrong single author Moran gets applied in the export as we use the verbatim data.
There is no way to influence this in the clearinghouse as its verbatim, it would need to be done in the source data files.

BUT as we have the new version deployed I would recommend we do not use any verbatim data in the exports anymore.
This a) gets us closer to reality and what will be exposed in the new portal and API and b) it allows to use decisions to apply changes

**Comment by gdower** [comment]
>     * [x]  Fixes in **Identical genus** (four split genera), detailed analyses:
>       for attention of @gdower
>       csv source vs CoL-draft
>       Cheilanthes 5+1+24+50=82 vs 82
>       Grammitis 35+6+4+1=46   vs   46
> 
> 
> Doryopteris 7+9+30=46 vs 40 = **6 spp LOST:**
> _from Doryopteris p. p._
> Doryopteris pedatoides (Desv.) Kuhn
> Doryopteris pilosa (Poir.) Kuhn
> _from Doryopteris s. lat._
> Doryopteris cyclophylla A. R. Sm.
> Doryopteris davidsei A. R. Sm.
> Doryopteris jequitinhonhensis Salino
> Doryopteris trilobata J. Prado
> 
> They are only part of Doryopteris p. p. and Doryopteris s. lat., other spp passed successfully.
> 
> Vittaria 7+15=22 vs 12 = **10 spp LOST:**
> _from Vittari auct._
> Vittaria lloydiifolia Racib.
> Vittaria nervosa Christ
> Vittaria nymanii Hieron.
> Vittaria pachystemma Christ
> Vittaria parvula Bory
> Vittaria pluridichotoma Bonap.
> Vittaria scabricoma Copel.
> Vittaria semipellucida Hieron.
> Vittaria squamosipes Alderw.
> Vittaria subcoriacea Christ
> 
> It's only part of Vittari auct., 5 spp from this genus successfully passed in CoL2020-06-26.

This was fixed by re-syncing, but it's not known why the species were missing in the first sync. There might be a bug, so if we follow this nested sector approach with World Plants we need to keep an eye out for it.

**Comment by yroskov** [comment]
2020-06-29, YR made corrections in CSV source file:
1. Corrected rank for Marattiales (O | 7 | Marattiales Link). As result, the order and family Marattiaceae should be placed in right position.
2. Joined Vittaria in one batch of 22 spp
3. Corrected authorstrings in Lellingeria barbensis (Lellinger) A. R. Sm. et R. C. Moran and Sceptridium rugulosum (W.H.Wagner) Skoda & Holub
4. Corrected authorstrings in Asplenium octoploideum Van Den Heede & Viane
Asplenium x chasmophilum Van Den Heede & Viane
Asplenium x ligusticum R. Bernardello, Marchetti, Van Den Heede & Viane

Geoff will run crawler and do a new import as GSD 1140.

**Comment by yroskov** [comment]
2020-06-29
**TASKS** after re-import:
![image](https://user-images.githubusercontent.com/28574252/86053178-bd3e0e00-ba1d-11ea-8cf1-3046dbcc9465.png)

ACC-SYN diff acc, same auth: Cystopteris | fragilis | (L.) Bernh. is marked as Amb Syn. No other decisions needed.

**Comment by yroskov** [comment]
Re-adjustments in Assembly failed for order Marattiales. Reported in GitHub as Assembly: Type Error e is null #773 (https://github.com/CatalogueOfLife/backend/issues/773 )

**Comment by mdoering** [comment]
@yroskov @gdower if source files have problems or are corrected, should we not create and discuss issues in the respective data repository instead of this general one? It would also be good to then link to actual commits that fix data. It seems the ferns repo isnt used much lately: https://github.com/CatalogueOfLife/data-world-ferns
So where are the changes being applied to?

**Comment by yroskov** [comment]
- [ ] Issue: Subspecies Assigned

  | dfedd75b-9a0e-5797-9de0-3ceb358a4e5c
-- | --

**Comment by yroskov** [comment]
**2020-07-07 Checks of Catalogue of Life: 2020-07-06 Beta at http://dev4.species.id:2204/col_plus/**

Previously reported content problems have been fixed.

@gdower
- [ ] Add portion "Beta" in the title of the product

- [ ] Type infraspecies (authonym) should have no authorstring:
_In 2020-07-06 Beta_: Lycopodium clavatum subsp. clavatum **L.** (accepted name) 
_Should be_: Lycopodium clavatum subsp. clavatum (accepted name) 

- [ ] Creation of references. Author of a reference should include full portion, which stays after brackets:
Example 
Grammitis magellanica f. nana (Brack.) **Sota ex T. R. Dudley** (accepted name)
http://dev4.species.id:2204/col_plus/details/species/id/0e3b782ef96c3ff97b5fc9869a61cb82/source/tree 
Ref in 2020-07-06 Beta: Author: Sota
Should be:                      Author: Sota ex T. R. Dudley

**Comment by gdower** [comment]
Beta will get added to the final release by my release SQL. This isn't a release.

**Comment by yroskov** [comment]
- [ ] Sync of Polipodiales failed
![image](https://user-images.githubusercontent.com/28574252/86844299-7e3b3880-c06d-11ea-80a8-5127a3c15290.png)

**Comment by yroskov** [comment]
**2020-07-08**

- [ ] Doryopteris sectors are broken now:

![image](https://user-images.githubusercontent.com/28574252/86942466-c78d9580-c10a-11ea-9cd0-3e965e8d9987.png)

It's not clear to me how to re-assemble Doryopteris. No sector options available now:
![image](https://user-images.githubusercontent.com/28574252/86942724-1a674d00-c10b-11ea-9cf5-7aff367bc8cc.png)

![image](https://user-images.githubusercontent.com/28574252/86942779-2e12b380-c10b-11ea-8beb-add1fbaf3ed3.png)

**Comment by yroskov** [comment]
All 3 genera:
Cheilanthes
Doryopteris
Grammitis
are split in assembly tree again. DISGUSTING!

**Comment by mdoering** [comment]
Manually fixing broken sectors is an important outstanding UI issue: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/547 similar to manually fixing broken decisions: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/523

We can use the API directly in those cases to assign a source taxon id (subject id). 
The ferns dataset was imported yesterday and the day before without the auto-rematch option. Have you tried to rematch?

**Comment by mdoering** [comment]
Because we now have multiple identical `Doryopteris` in the assembly tree the sector targets do not match automatically:

```
     "id": 115587,
      "target": {
        "name": "Doryopteris",
        "authorship": "J.Sm.",
        "rank": "genus"
      },

     "id": 115586,
      "target": {
        "name": "Doryopteris",
        "authorship": "J.Sm.",
        "rank": "genus"
      },

```

Well, there actually is just one genus in the tree:
http://api.catalogue.life/dataset/3/nameusage/search?rank=genus&q=Doryopteris

```
       "id": "4c365e96-ce54-41a7-81eb-be732733f51e",
        "sectorKey": 115576,
        "name": {
          "scientificName": "Doryopteris",
          "authorship": "J. Sm.",
          "rank": "genus",
          "code": "botanical",
```

Maybe the matching does not ignore whitespace as the authorships differ by a space? That should not be the case, but the new verbatim authorship change probably has introduced that. Hm no, tried and it doesnt make a difference. It actually seems the rematch button does only trigger a subject rematch, not a target one

**Comment by yroskov** [comment]
Rematch does not work:

![image](https://user-images.githubusercontent.com/28574252/86969801-f835f500-c133-11ea-87a2-8f63dcd0eb87.png)

**Comment by mdoering** [comment]
> All 3 genera:
Cheilanthes
Doryopteris
Grammitis
are split in assembly tree again. DISGUSTING!

I can only see Cheilanthes being split, Doryopteris exists only once.
And the reason Doryopteris is fine but Cheilanthes isn't is that Cheilanthes misses the blocking decisions!
The main sector `Polypodiales` therefore copies all instances of genus Cheilanthes over to the assembly tree.

**Comment by yroskov** [comment]
Geoff and me exercised with blocking Doryopteris in GSD today (that's why it's a sigle entry in assembly tree). However, blocking did not resolve a main problem: all species from "Doryopteris ." and "Doryopteris p.p." are missing in assembly.

Attempt to bring missing species in Doryopteris J.Sm. ended with a bug report:
![image](https://user-images.githubusercontent.com/28574252/86973635-89a86580-c13a-11ea-8286-a8b626aceed4.png)

**Comment by mdoering** [comment]
This is not a bug, its a bad request. You cannot create multiple sectors in a single project that share the same source taxon

**Comment by mdoering** [comment]
@thomasstjerne can we show a more user friendly message in case of 400 errors? Maybe just "Bad request" and show the error details on demand only?

**Comment by mdoering** [comment]
I just blocked the extra Doryopteris genera, deleted the old 2 genus sectors and recreated them with a union and then synced both. It all worked fine as expected and the result looks good to me:

<img width="1865" alt="Screenshot 2020-07-09 at 13 54 53" src="https://user-images.githubusercontent.com/327505/87037028-ea43ab00-c1eb-11ea-80f5-083e13d85fc5.png">
