### ISSUE TITLE
World Plants aka "WP dev" 2209 of 2020-09-24: test report #173

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#174]
Test of the resource at https://data.catalogue.life/dataset/2209/issues
(WP ver. 2020-06-14)

Feature: the crawler was adjusted, new IDs implemented; new import & indexing

**Comment by yroskov** [comment]
**Classification**

- [x] All additional fams are in place. WP classification looks OK.

- [ ] Strange: classification in 1141 on prod was changed since my sector re-assembly. It is identical to 2209 now. Check with Geoff.

- [ ] Att YR! check ord Brassicales after sector's rebuild (WP Capparales --> APG Brassicales)

**Comment by yroskov** [comment]
**Issues**

- [ ] Subspecies assigned. Incorrect assignment: 
![image](https://user-images.githubusercontent.com/28574252/94174146-85970480-fe5a-11ea-8dad-586771b0e164.png)

- [ ] Indetermined
YR: block names with missing epithet
https://data.catalogue.life/dataset/2209/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=indetermined&limit=50&offset=50&reverse=false

- [ ] Parent name mismatch
https://data.catalogue.life/dataset/2209/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=parent%20name%20mismatch&limit=50&offset=0&reverse=false
1. Cases where genus misspelled as uninomial vs binomial in the source: Aetheorhiza vs Aetheo**rr**hiza bulbosa; Rhyticaryum vs **Ry**ticaryum elegans 
2. Mismatch (!!): Rumicastrum vs Calandrinia arenicola, Calandrinia baccata, ...

**Comment by yroskov** [comment]
- [ ] Unparsable Authorship 
![image](https://user-images.githubusercontent.com/28574252/94192829-17ac0680-fe75-11ea-9231-55756b00edd0.png)

Nightmare. As a first step: exclude all tribes & subtribes. 
However, split genera will remain (Lactuca p. p. & Lactuca p. p.; Scorzonera s. lat. and Scorzonera s. lat.).

**Comment by yroskov** [comment]
- [ ] Inconsistent Name 
Partly will be resolved after excluding tribes & subtribes. 
Do not see problems in subgenus syns.

- [ ] Not interpreted, 662 cases
Lot of different cases

- [ ] Multi Word Epithet, 4526
All (?) names with hybrid cross. It's OK.

**Comment by mdoering** [comment]
is world plants is in a worse state than expected?

**Comment by mdoering** [comment]
would it help if we added a SYNC_EXCLUDE_RANKS setting for an entire source dataset, e.g. to exclude all tribes?

**Comment by yroskov** [comment]
Many additional problems because of intermediate rank taxa and synonymy with uninomials.

**Comment by yroskov** [comment]
> would it help if we added a SYNC_EXCLUDE_RANKS setting for an entire source dataset, e.g. to exclude all tribes?

Yeah, it should be sorted on a level of crawling (@gdower?)  or as SYNC_EXCLUDE_RANKS setting for an entire source dataset.

**Comment by mdoering** [comment]
Please try to exclude taxa from the _Sync_, not when creating the source dataset archive. If world plants has tribes they should be included in the imported data.

Alternatively to SYNC_EXCLUDE_RANKS on a dataset level we could do an exclude rank on a sector. That is more flexible and simpler to implement, but it needs attention on every sector. We can do it once with a script though to update all WP sectors to exclude tribes

**Comment by yroskov** [comment]
>exclude rank on a sector

It is not easy to do in a current design of the Clearinghouse. 
I have following report: 
![image](https://user-images.githubusercontent.com/28574252/94201973-69a75900-fe82-11ea-83af-eab27e635060.png)

How I can pick up a sector from this report? How I can easy switch to the page, where I can exclude rank in the sector? How I can go back to the report and resolve next name/taxon? Ofully complicated.

**Comment by yroskov** [comment]
- [ ] 3 names need to be fixed:
![image](https://user-images.githubusercontent.com/28574252/94204574-1daae300-fe87-11ea-8924-e016eab07e79.png)

**Comment by yroskov** [comment]
**TASKS** 
(checking 1141, it suppose to be identical now to 2209; unable to check Tasks in 2209, because it is out of id3 project)

![image](https://user-images.githubusercontent.com/28574252/94299378-34a41080-ff2d-11ea-800a-2ca49ca57345.png)

**Comment by yroskov** [comment]
- [ ] Hmm, 10,017(!) broken decisions. Reason? How to deal with it?

**Comment by yroskov** [comment]
- [x] Identical order, 2
No actions. It's about synonyms.

- [x] Identical superfamily, 1
Jacea as a synonym with superfamily rank in Malpigiales and Asterales. Might be fake, might be true. 

- [x] Identical family, >50
No actions. All synonyms.

**Comment by yroskov** [comment]
- [ ] Identical genus, 14
11 split genera in Apiaceae like that:
![image](https://user-images.githubusercontent.com/28574252/94301091-aaa97700-ff2f-11ea-950d-6f28e6bc210a.png)

**We need to unite them. How to procced?**

1 split genus in Caryophyllaceae:
![image](https://user-images.githubusercontent.com/28574252/94301250-dc224280-ff2f-11ea-9205-8913c82e8ac5.png)

2 strange cases in the report:
![image](https://user-images.githubusercontent.com/28574252/94301345-0542d300-ff30-11ea-9205-0eda454303c4.png)

**Comment by yroskov** [comment]
- [x] Identical subgenus, 7
No actions. All synonyms.

**Comment by yroskov** [comment]
- [ ] Any uninomial, >50
Only accepted need to be addressed.
https://data.catalogue.life/catalogue/3/dataset/1141/duplicates?category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted

New cases (not as listed above) with authorstrings like these: clade, chinense clade, clade [HAP clade], group, subgroup, lineage, unplaced. All are unnamed OTUs. 

**If we remove Tribe & Subtribe ranks, majority of these cases disappear.**

![image](https://user-images.githubusercontent.com/28574252/94301840-e264ee80-ff30-11ea-81a8-fa6c753abb27.png)

Plus previously mentioned split genera (p.p., p.min.p.).

**Comment by yroskov** [comment]
**2020-10-05**
_Geoff run his script which **re-matched sectors**._

Confirmed positive tests for:

Rhamnaceae, Elaeagnaceae, Dirachmaceae, Juncaceae, 
Paracryphiales, Sapindales, Oxalidales, Nymphaeales, Myrtales

Malvales, Geraniales, Gentianales, Laurales, Metteniusaceae, 
Oncothecaceae, Icacinaceae, Gunnerales, Myricaceae, Casuarinaceae

Juglandaceae, Chesniella, Astragalus, Quillajaceae, Polygalaceae
Eupteleaceae, Ranunculales, Escalloniales, Theaceae, Tetrameristaceae

**_Re-matched all sectors_**

**Broken sectors, 4:**

- [x] **Surianaceae** - fam missing in the source files. We'll use sync of previous version.

- [x] **Bretschneideraceae** - synonym of Akaniaceae. Only one child Bretschneidera should be placed in Akaniaceae (as in source file). Fixed: killed sector & deleted family Bretschneideraceae; synced Akinaceae

- [ ] Brassicales

- [ ] Myrtales

**Comment by yroskov** [comment]
**TASKS** 2020-10-05

![image](https://user-images.githubusercontent.com/28574252/95115574-51013380-070b-11eb-9d91-95bd0b91eeab.png)
