### ISSUE TITLE
World Plants of 2020-09-25: test report 2020-10-05

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/data#182]
**2020-10-05**
_Geoff run his script which **re-matched sectors**._

**Comment by yroskov** [comment]
Confirmed positive tests for:

Rhamnaceae, Elaeagnaceae, Dirachmaceae, Juncaceae, 
Paracryphiales, Sapindales, Oxalidales, Nymphaeales, Myrtales

Malvales, Geraniales, Gentianales, Laurales, Metteniusaceae, 
Oncothecaceae, Icacinaceae, Gunnerales, Myricaceae, Casuarinaceae

Juglandaceae, Chesniella, Astragalus, Quillajaceae, Polygalaceae
Eupteleaceae, Ranunculales, Escalloniales, Theaceae, Tetrameristaceae

**_Re-matched all sectors_**

**Broken sectors, 4:**

- [x] **Surianaceae** - fam missing in the source files. We'll use sync of previous version.

- [x] **Bretschneideraceae** - synonym of Akaniaceae. Only one child Bretschneidera should be placed in Akaniaceae (as in source file). Fixed: killed sector & deleted family Bretschneideraceae; synced Akinaceae

- [x] **Brassicales** - in new WP version, Brassicales is a syn of Capparales. CoL follows APG Brassicales (= syn Capparales). Re-assembled & synced.

- [x] **Myrtales** - re-assembled & synced.

**Comment by yroskov** [comment]
**TASKS** 2020-10-05
I have re-matched decisions in WP, and deleted all(?) which remained broken.  

![image](https://user-images.githubusercontent.com/28574252/95115574-51013380-070b-11eb-9d91-95bd0b91eeab.png)

**Comment by yroskov** [comment]
- [x] Manuscript names: all 996 accepted names are marked as prov. acc.

**Comment by mdoering** [comment]
> Manuscript names: all 996 accepted names are marked as prov. acc.

Should we let the sync process assign a prov.acc. status automatically for names of type manuscript?
Manual decisions could then focus on those which are false manuscript names which I suppose is a _lot_ less work.

**Comment by yroskov** [comment]
No. This should be managed manually.

**Comment by yroskov** [comment]
**2020-10-08**, the same dataset, Tasks (continue)

- [ ] **ACC-SYN (diff acc, diff auth)**  https://data.catalogue.life/catalogue/3/dataset/1141/duplicates?acceptedDifferent=true&authorshipDifferent=true&category=binomial&limit=500&minSize=2&mode=STRICT&offset=1000&status=accepted&status=synonym&withDecision=true

**There are synonyms in this report with empty authorstrings** (blocked). 
![image](https://user-images.githubusercontent.com/28574252/95507948-d7ba4880-0977-11eb-8409-638397209bf8.png)

Seems, authorstrings missing for various reasons (crawler was unable to handle atypical format, crawler's mistake, etc.). Some authorstrings were deliberately removed by the Clearinghouse (e.g. Corydalis sewerzowii sensu Aitch., Asclepias ovata Auct. ex Steud.) - these names should be marked as Misapplied Names in CoL. Well, because I do not know what empty authorstring means, I have blocked all synonyms with empty authorstrings in CoL.

**Comment by mdoering** [comment]
Remember that we differ between a Name and a Taxon/Synonym aka NameUsage.
The names authorship should not have a taxonomic notion, so `sensu Aitch.` gets transferred from the _Name.authorship_, to the Synonym.namePhrase.

The final Synonym.label should have all the bits together again. If not there is sth wrong indeed.
The 2 usages for Corydalis sewerzowii do not have a namePhrase though: https://api.catalogue.life/dataset/1141/nameusage/search?q=Corydalis%20sewerzowii

**Comment by yroskov** [comment]
ACC-SYN infra (diff acc, same auth)

- [ ] **Missing genus name in the report** 
https://data.catalogue.life/catalogue/3/dataset/1141/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=trinomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym&withDecision=false
![image](https://user-images.githubusercontent.com/28574252/95515953-135b0f80-0984-11eb-9831-3bb9a71a44a9.png)

**No ideas what's happened here.**

**Comment by mdoering** [comment]
The [verbatim data](https://api.catalogue.life/dataset/1141/verbatim/1014847) for the _Corydalis sewerzowii_ synonym has no namePhrase:
```
 "id": 1014847,
  "datasetKey": 1141,
  "line": 27207,
  "file": "Synonym.tsv",
  "type": "col:Synonym",
  "terms": {
    "col:nameID": "Ranunculales-Papaveraceae-Fumarioideae-Corydalis-subspecies-aitchisonii-Popov-Corydalis sewerzowii sensu Aitch.",
    "col:status": "synonym",
    "col:taxonID": "Ranunculales-Papaveraceae-Fumarioideae-Corydalis-subspecies-aitchisonii-Popov"
  }
```

and the name also does not have any authorship in its [verbatim data](https://api.catalogue.life/dataset/1141/verbatim/1599203):
```
{
  "id": 1599203,
  "datasetKey": 1141,
  "line": 44801,
  "file": "Name.tsv",
  "type": "col:Name",
  "terms": {
    "col:ID": "Ranunculales-Papaveraceae-Fumarioideae-Corydalis-subspecies-aitchisonii-Popov-Corydalis sewerzowii sensu Aitch.",
    "col:code": "botanical",
    "col:genus": "Corydalis",
    "col:referenceID": "34030",
    "col:scientificName": "Corydalis sewerzowii",
    "col:publishedInPage": "32",
    "col:specificEpithet": "sewerzowii"
  }
}
```

So its a crawler issues

**Comment by yroskov** [comment]
**Tasks 2020-10-09**

![image](https://user-images.githubusercontent.com/28574252/95618847-532d0000-0a33-11eb-996b-4b0991956474.png)

SYN sp (diff acc, diff auth) has a longest list of cases.

Tasks for infraspecies left unresolved because of bug CatalogueOfLife/clearinghouse-ui#747: genus is missing in the report.

Att!: Tasks ACC-SYN infra (diff acc, diff auth) and ACC-SYN infra (diff acc, same auth) have been resolved by mistake (I have deleted decision, one by one, but they still stay in the report).

https://data.catalogue.life/catalogue/3/dataset/1141/duplicates?acceptedDifferent=true&authorshipDifferent=true&category=trinomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym&withDecision=true  

https://data.catalogue.life/catalogue/3/dataset/1141/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=trinomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym&withDecision=true

**Comment by yroskov** [comment]
- [ ] Some trinomials in synonyms have no infraspecific marker (perhaps, non-standard marker used in the source)
https://data.catalogue.life/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=rank%20invalid&limit=100&offset=0

Example: Helianthemum apenninum rothmaleri (Villar ex Rothm.) M. Mayor & M. Fernández (acc Helianthemum rothmaleri)
in the source: = Helianthemum apenninum nothossp. rothmaleri

**Comment by yroskov** [comment]
**Tasks 2020-10-12:**

![image](https://user-images.githubusercontent.com/28574252/95785002-8d4c0b00-0c9a-11eb-88b1-4670d6d8f444.png)
